/*
 * Hardware pin assignments for the WULPUS MSP430 firmware.
 */

#ifndef HARDWARE_H_
#define HARDWARE_H_

#include "driverlib.h"

// Select your BOARD - only one at a time
// #define WULPUS_BOARD_ETH_CLASSIC
#define WULPUS_BOARD_UBC_VLASSIC_V1_2

// LED indicator on the acquisition PCB (P1.5)
#if defined(WULPUS_BOARD_UBC_VLASSIC_V1_2)
#define GPIO_PORT_LED_MSP430 GPIO_PORT_P5
#define GPIO_PIN_LED_MSP430 GPIO_PIN1
#elif defined(WULPUS_BOARD_ETH_CLASSIC)
#define GPIO_PORT_LED_MSP430 GPIO_PORT_P1
#define GPIO_PIN_LED_MSP430 GPIO_PIN5
#endif

// BLE ready signal from the nRF52 (P4.4)
#if defined(WULPUS_BOARD_UBC_VLASSIC_V1_2)
#define GPIO_PORT_BLE_READY GPIO_PORT_P1
#define GPIO_PIN_BLE_READY GPIO_PIN5
#elif defined(WULPUS_BOARD_ETH_CLASSIC)
#define GPIO_PORT_BLE_READY GPIO_PORT_P4
#define GPIO_PIN_BLE_READY GPIO_PIN4
#endif

// Handshake line to the nRF52 indicating data availability (P4.0)
#if defined(WULPUS_BOARD_UBC_VLASSIC_V1_2)
#define GPIO_PORT_DATA_READY GPIO_PORT_P1
#define GPIO_PIN_DATA_READY GPIO_PIN4
#elif defined(WULPUS_BOARD_ETH_CLASSIC)
#define GPIO_PORT_DATA_READY GPIO_PORT_P4
#define GPIO_PIN_DATA_READY GPIO_PIN0
#endif

// nRF52 SPI interface (MSP430 as slave on EUSCI_A1)
#if defined(WULPUS_BOARD_UBC_VLASSIC_V1_2)
#define GPIO_PORT_NRF_SPI_MOSI GPIO_PORT_P4
#define GPIO_PIN_NRF_SPI_MOSI GPIO_PIN3
#define GPIO_PORT_NRF_SPI_MISO GPIO_PORT_P4
#define GPIO_PIN_NRF_SPI_MISO GPIO_PIN4
#define GPIO_PORT_NRF_SPI_CLK GPIO_PORT_P4
#define GPIO_PIN_NRF_SPI_CLK GPIO_PIN1
#define GPIO_PORT_NRF_SPI_CS GPIO_PORT_P4
#define GPIO_PIN_NRF_SPI_CS GPIO_PIN2
#elif defined(WULPUS_BOARD_ETH_CLASSIC)
#define GPIO_PORT_NRF_SPI_MOSI GPIO_PORT_P1
#define GPIO_PIN_NRF_SPI_MOSI GPIO_PIN2
#define GPIO_PORT_NRF_SPI_MISO GPIO_PORT_P1
#define GPIO_PIN_NRF_SPI_MISO GPIO_PIN3
#define GPIO_PORT_NRF_SPI_CLK GPIO_PORT_P2
#define GPIO_PIN_NRF_SPI_CLK GPIO_PIN0
#define GPIO_PORT_NRF_SPI_CS GPIO_PORT_P2
#define GPIO_PIN_NRF_SPI_CS GPIO_PIN1
#endif

// HV MUX SPI interface (MSP430 as master on EUSCI_B1)
#define GPIO_PORT_HV_MUX_SPI GPIO_PORT_P5
#define GPIO_PIN_HV_MUX_CLK GPIO_PIN4
#define GPIO_PIN_HV_MUX_MOSI GPIO_PIN5
#define LE_PIN_PORT GPIO_PORT_P5
#define LE_PIN GPIO_PIN7

// Power control signals
#if defined(WULPUS_BOARD_UBC_VLASSIC_V1_2)
#define GPIO_PORT_RX_POWER GPIO_PORT_P2
#define GPIO_PIN_RX_POWER GPIO_PIN2
#define GPIO_PORT_HV_SUPPLY GPIO_PORT_P6
#define GPIO_PIN_HV_SUPPLY GPIO_PIN6
#define GPIO_PORT_RX_ENABLE GPIO_PORT_P6
#define GPIO_PIN_RX_ENABLE GPIO_PIN2
#define GPIO_PORT_SWITCH_ENABLE GPIO_PORT_P7
#define GPIO_PIN_SWITCH_ENABLE GPIO_PIN4
#define GPIO_PORT_HV_DC_ENABLE GPIO_PORT_P7
#define GPIO_PIN_HV_DC_ENABLE GPIO_PIN0
#elif defined(WULPUS_BOARD_ETH_CLASSIC)
#define GPIO_PORT_RX_POWER GPIO_PORT_P1
#define GPIO_PIN_RX_POWER GPIO_PIN6
#define GPIO_PORT_HV_SUPPLY GPIO_PORT_P2
#define GPIO_PIN_HV_SUPPLY GPIO_PIN2
#define GPIO_PORT_RX_ENABLE GPIO_PORT_P6
#define GPIO_PIN_RX_ENABLE GPIO_PIN0
#define GPIO_PORT_SWITCH_ENABLE GPIO_PORT_P6
#define GPIO_PIN_SWITCH_ENABLE GPIO_PIN4
#define GPIO_PORT_HV_DC_ENABLE GPIO_PORT_P6
#define GPIO_PIN_HV_DC_ENABLE GPIO_PIN5
#endif

#endif /* HARDWARE_H_ */
