# Enable C++ support
CONFIG_CPP=y

# Debugging
CONFIG_DEBUG=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_CORTEX_M_DEBUG_MONITOR_HOOK=y
CONFIG_SEGGER_DEBUGMON=y
# DEBUG_COREDUMP=y
# DEBUG_COREDUMP_BACKEND_LOGGING=y

# Show Utilization
# CONFIG_THREAD_ANALYZER=y
# CONFIG_THREAD_ANALYZER_USE_PRINTK=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5

# Enable BT
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="WULPUS_PROBE_3"
CONFIG_BT_NUS=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
# Optimizing for high throughput
CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=10
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400
CONFIG_BT_ATT_PREPARE_COUNT=5
# Enable longer BT messages
CONFIG_BT_L2CAP_TX_MTU=220
CONFIG_BT_BUF_ACL_TX_SIZE=224
CONFIG_BT_BUF_ACL_RX_SIZE=230
CONFIG_BT_CTLR_DATA_LENGTH_MAX=211

# CONFIG_BT_L2CAP_TX_BUF_COUNT=26
# CONFIG_BT_BUF_EVT_RX_COUNT=26
# CONFIG_BT_BUF_ACL_TX_COUNT=24
# CONFIG_BT_CONN_TX_MAX=24

# Enable GPIO
CONFIG_GPIO=y

# Log to RTT
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_PRINTK=y

# Enable Asserts
CONFIG_ASSERT=y

# Enable SPI Master role at SPI1
CONFIG_NRFX_SPIM1=y

# Enable Timer 3 and 4 for SPI automation
CONFIG_NRFX_TIMER3=y
CONFIG_NRFX_TIMER4=y

# Enable PPI (Programmable Peripheral Interconnect)
CONFIG_NRFX_PPI=y

# Increase System Workqueue stack size (data_ready_work_handler runs here)
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048